version: '3.1'

services:

  site-vitrine:
    restart: always
    image: nginx-prod-site-vitrine
    expose:
      - "80"
    networks:
      - traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.frontend.rule=Host:centrale-fitness.fr.nf"

  intra-gerant:
    restart: always
    image: nginx-prod-intra-gerant
    expose:
      - "80"
    networks:
      - traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.frontend.rule=Host:intra-gerant.centrale-fitness.fr.nf"

  intra-admin:
    image: nginx-prod-intra-admin
    expose:
      - "80"
    networks:
      - traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.frontend.rule=Host:intra-admin.centrale-fitness.fr.nf"

  backend-java:
    restart: always
    image: java-prod-server
    expose:
      - "8082"
      - "8080"
      - "10000"
      - "5445"
      - "6660"
      - "8083"
    depends_on:
      - mango
    networks:
      - traefik
      - database
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.api.web.port=8280"
      - "traefik.api.web.frontend.rule=Host:api.web.centrale-fitness.fr.nf"
      - "traefik.api.mobile.port=8080"
      - "traefik.api.mobile.frontend.rule=Host:api.mobile.centrale-fitness.fr.nf"
      - "traefik.api.module.port=10000"
      - "traefik.api.module.frontend.rule=Host:api.module.centrale-fitness.fr.nf"
      - "traefik.api.intranet.port=5445"
      - "traefik.api.intranet.frontend.rule=Host:api.intranet.centrale-fitness.fr.nf"
      - "traefik.api.image.port=6660"
      - "traefik.api.image.frontend.rule=Host:api.image.centrale-fitness.fr.nf"
      - "traefik.api.admin.port=8083"
      - "traefik.api.admin.frontend.rule=Host:api.admin.centrale-fitness.fr.nf"

  traefik:
    restart: always
    image: traefik:latest
    command: --web --docker --logLevel=DEBUG
    networks:
      - traefik
      - database
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/traefik.toml:/traefik.toml"
      - "$PWD/acme.json:/acme.json"
    labels:
      - "traefik.enable=false"

  mango:
    restart: always
    image: mongo:latest
    networks:
      - database
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../backup/persistent_volume/:/data/db"
    labels:
      - "traefik.enable=false"

  mango-tools:
    image: mango-backup-tools
    networks:
      - database
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../backup/files/:/opt/app"
    labels:
      - "traefik.enable=false"

networks:
  traefik:
    driver: bridge
  database:
    driver: bridge